# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x0cinventory.v1\"=\n\x18\x43heckAvailabilityRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"w\n\x19\x43heckAvailabilityResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x1a\n\x12requested_quantity\x18\x02 \x01(\x05\x12\x1a\n\x12\x61vailable_quantity\x18\x03 \x01(\x05\x12\x11\n\tavailable\x18\x04 \x01(\x08\x32x\n\x10InventoryService\x12\x64\n\x11\x43heckAvailability\x12&.inventory.v1.CheckAvailabilityRequest\x1a\'.inventory.v1.CheckAvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_start=33
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_end=94
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_start=96
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_end=215
  _globals['_INVENTORYSERVICE']._serialized_start=217
  _globals['_INVENTORYSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
