# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub:
    """Order Service contract for the gRPC version.
    gRPC equivalent of `POST /orders` and `GET /health` in the REST version.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/order.v1.OrderService/PlaceOrder',
                request_serializer=order__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=order__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/order.v1.OrderService/Health',
                request_serializer=order__pb2.HealthRequest.SerializeToString,
                response_deserializer=order__pb2.HealthResponse.FromString,
                _registered_method=True)


class OrderServiceServicer:
    """Order Service contract for the gRPC version.
    gRPC equivalent of `POST /orders` and `GET /health` in the REST version.
    """

    def PlaceOrder(self, request, context):
        """Places an order after checking stock with InventoryService.CheckAvailability.

        Error statuses:
        INVALID_ARGUMENT    - item_id is empty or quantity < 1
        NOT_FOUND           - item_id is not in the catalog (from Inventory)
        FAILED_PRECONDITION - not enough units in stock (from Inventory)
        DEADLINE_EXCEEDED   - Inventory did not answer before the Order -> Inventory deadline
        UNAVAILABLE         - Inventory could not be reached
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness check, used to show the Order Service is still up after Inventory failures.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=order__pb2.PlaceOrderRequest.FromString,
                    response_serializer=order__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=order__pb2.HealthRequest.FromString,
                    response_serializer=order__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.v1.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.v1.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService:
    """Order Service contract for the gRPC version.
    gRPC equivalent of `POST /orders` and `GET /health` in the REST version.
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/PlaceOrder',
            order__pb2.PlaceOrderRequest.SerializeToString,
            order__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/Health',
            order__pb2.HealthRequest.SerializeToString,
            order__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
