# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x08order.v1\"6\n\x11PlaceOrderRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"Y\n\x12PlaceOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07item_id\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"\x0f\n\rHealthRequest\"\x92\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x01\x12\x18\n\x10orders_confirmed\x18\x04 \x01(\x05\x12\x17\n\x0forders_rejected\x18\x05 \x01(\x05\x12\x18\n\x10inventory_errors\x18\x06 \x01(\x05\x32\x94\x01\n\x0cOrderService\x12G\n\nPlaceOrder\x12\x1b.order.v1.PlaceOrderRequest\x1a\x1c.order.v1.PlaceOrderResponse\x12;\n\x06Health\x12\x17.order.v1.HealthRequest\x1a\x18.order.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLACEORDERREQUEST']._serialized_start=25
  _globals['_PLACEORDERREQUEST']._serialized_end=79
  _globals['_PLACEORDERRESPONSE']._serialized_start=81
  _globals['_PLACEORDERRESPONSE']._serialized_end=170
  _globals['_HEALTHREQUEST']._serialized_start=172
  _globals['_HEALTHREQUEST']._serialized_end=187
  _globals['_HEALTHRESPONSE']._serialized_start=190
  _globals['_HEALTHRESPONSE']._serialized_end=336
  _globals['_ORDERSERVICE']._serialized_start=339
  _globals['_ORDERSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
